// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFh81xHm1UnOZDz9cqyGUdlSl96NSwxVs',
    appId: '1:658569844340:web:feaf87195ffc165c682321',
    messagingSenderId: '658569844340',
    projectId: 'outset-9b6bd',
    authDomain: 'outset-9b6bd.firebaseapp.com',
    storageBucket: 'outset-9b6bd.appspot.com',
    measurementId: 'G-F7DLML0MPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZYYc7h01pdeI2-83cxgEXWLodVK3qXc',
    appId: '1:658569844340:android:df9a15dcfc14f0d8682321',
    messagingSenderId: '658569844340',
    projectId: 'outset-9b6bd',
    storageBucket: 'outset-9b6bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWztkbH_bJEWXPlEcJSaJpB141CdugPQQ',
    appId: '1:658569844340:ios:6a239926f5a0888e682321',
    messagingSenderId: '658569844340',
    projectId: 'outset-9b6bd',
    storageBucket: 'outset-9b6bd.appspot.com',
    iosClientId: '658569844340-e88o8loc5jgj22akf3ua8jia1jqrcvko.apps.googleusercontent.com',
    iosBundleId: 'com.example.outset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWztkbH_bJEWXPlEcJSaJpB141CdugPQQ',
    appId: '1:658569844340:ios:6a239926f5a0888e682321',
    messagingSenderId: '658569844340',
    projectId: 'outset-9b6bd',
    storageBucket: 'outset-9b6bd.appspot.com',
    iosClientId: '658569844340-e88o8loc5jgj22akf3ua8jia1jqrcvko.apps.googleusercontent.com',
    iosBundleId: 'com.example.outset',
  );
}
